swagger: "2.0"
info:
  description: "This is a server...."
  version: "1.0.0"
  title: "Swagger crypto whisper"
basePath: "/"
tags:
- name: "CryptoAPI"
  description: "share your message with everyone"
schemes:
- "https"
- "http"
paths:
  /getKey/{adress}:
    get:
      tags:
      - "CryptoAPI"
      summary: "Find message key by ID"
      description: "Returns a single pet"
      operationId: "getKey"
      produces:
      - "application/json"
      parameters:
      - name: "adress"
        in: "path"
        description: "return encripted message for you to verify your private key"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/keyValidationResp"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
  /getMessages/{adress}:
    get:
      tags:
      - "CryptoAPI"
      summary: "Find message key by ID"
      description: "Returns a single pet"
      operationId: "getPetById"
      produces:
      - "application/json"
      parameters:
      - name: "adress"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/error"
        "404":
          description: "Pet not found"
  /sendMessage/{adress}:
    post:
      tags:
      - "CryptoAPI"
      summary: "Updates a pet in the store with form data"
      description: ""
      operationId: "updatePetWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "adress"
        in: "path"
        description: "ID of pet that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - $ref: '#/definitions/encMessage'
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/error"
        "404":
          description: "Pet not found"
          
definitions:
  error:
    type: "object"
    properties:
      description:
        type: "string"
  encMessage:
    type: "object"
    properties:
      encMessage:
        type: "string"
  keyValidationResp:
    type: "object"
    required:
    - "id"
    - "message"
    properties:
      id:
        type: "integer"
        format: "int64"
      message:
        type: "string"
        example: "doggie"
      validDate:
        type: "string"
        example: "doggie"
externalDocs:
  description: "LOL"
  url: "https://github.com/DisorderCultist/cryptoWhisper"